### PR TITLE
Fix default exchange declaration and useage

### PR DESCRIPTION
**Pull request by moenzuel**

### CODE REVIEW

**Comment by lucacorti** [comment]
Hei @moenzuel thanks for the PR.

Sorry for the delay in getting back to you. Can you elaborate on the issue you are addressing please?

**Comment by moenzuel** [comment]
The default exchange already exists and errors when you try and redefine it. As an added magic bonus, binding to the default exchange is done automatically. My PR basically adds no-ops for the default exchange declare and bind.

**Comment by lucacorti** [comment]
Thanks for the explanation @moenzuel.

I have a pretty big refactor coming, which splits consumer/producer configuration and exchange/queue declaration which I think makes this issue not as relevant.

You might want to check out the `consumer_producer_pattern_flags` branch and see if this addresses your problem or if a revised PR could improve things there too.

**Comment by lucacorti** [comment]
@moenzuel I'm closing this since I'm releasing a complete rework of configuration with separate declarations and producer/consumer split.

**Pull request closed without merging**
